/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressBar: typeof import('./src/components/AddressBar.vue')['default']
    AddressSelect: typeof import('./src/components/AddressSelect.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    DisplayResult: typeof import('./src/components/DisplayResult.vue')['default']
  }
}
